/**
 * FocusFlow — Property-Based Tests
 * Uses Vitest (test runner) + fast-check (property-based testing)
 *
 * Only pure functions from app.js are tested here.
 * No DOM, no localStorage, no browser globals.
 */

import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import {
  createTask,
  addTask,
  toggleTask,
  deleteTask,
  filterTasks,
  clearCompleted,
} from '../app.js';

// ---------------------------------------------------------------------------
// Arbitraries
// ---------------------------------------------------------------------------

/** A non-empty string trimmed to a reasonable task title */
const titleArb = fc
  .string({ minLength: 1, maxLength: 80 })
  .map(s => s.trim())
  .filter(s => s.length > 0);

/** One of the three valid priority values */
const priorityArb = fc.constantFrom('low', 'medium', 'high');

/** A single valid Task generated by createTask */
const taskArb = fc.tuple(titleArb, priorityArb).map(([t, p]) => createTask(t, p));

/** An array of 0–20 valid tasks */
const tasksArb = fc.array(taskArb, { minLength: 0, maxLength: 20 });

/** A non-empty array of valid tasks (at least one) */
const nonEmptyTasksArb = fc.array(taskArb, { minLength: 1, maxLength: 20 });

// ---------------------------------------------------------------------------
// P-1: Size invariant
// Adding N valid tasks to an empty list results in a list of exactly N tasks.
// ---------------------------------------------------------------------------
describe('P-1: addTask size invariant', () => {
  it('adding N tasks to an empty list produces a list of length N', () => {
    fc.assert(
      fc.property(fc.array(taskArb, { minLength: 0, maxLength: 20 }), (newTasks) => {
        const result = newTasks.reduce((acc, task) => addTask(acc, task), []);
        expect(result).toHaveLength(newTasks.length);
      })
    );
  });

  it('adding one task increments the list length by exactly 1', () => {
    fc.assert(
      fc.property(tasksArb, taskArb, (existingTasks, newTask) => {
        const result = addTask(existingTasks, newTask);
        expect(result).toHaveLength(existingTasks.length + 1);
      })
    );
  });
});

// ---------------------------------------------------------------------------
// P-2: Filter purity
// filterTasks never mutates the original array.
// ---------------------------------------------------------------------------
describe('P-2: filterTasks does not mutate the original array', () => {
  const filterArb = fc.constantFrom('all', 'active', 'completed');

  it('the original tasks array is unchanged after filtering', () => {
    fc.assert(
      fc.property(tasksArb, filterArb, (originalTasks, f) => {
        const snapshot = JSON.stringify(originalTasks);
        filterTasks(originalTasks, f);
        expect(JSON.stringify(originalTasks)).toBe(snapshot);
      })
    );
  });

  it('filter "all" returns the same number of tasks as the original', () => {
    fc.assert(
      fc.property(tasksArb, (tasks) => {
        const result = filterTasks(tasks, 'all');
        expect(result).toHaveLength(tasks.length);
      })
    );
  });

  it('filter "active" + filter "completed" accounts for all tasks', () => {
    fc.assert(
      fc.property(tasksArb, (tasks) => {
        const active    = filterTasks(tasks, 'active');
        const completed = filterTasks(tasks, 'completed');
        expect(active.length + completed.length).toBe(tasks.length);
      })
    );
  });
});

// ---------------------------------------------------------------------------
// P-3: clearCompleted leaves no completed tasks
// ---------------------------------------------------------------------------
describe('P-3: clearCompleted removes all completed tasks', () => {
  it('result contains zero completed tasks', () => {
    fc.assert(
      fc.property(tasksArb, (tasks) => {
        const result = clearCompleted(tasks);
        const completedCount = result.filter(t => t.completed).length;
        expect(completedCount).toBe(0);
      })
    );
  });

  it('clears only completed tasks — incomplete tasks survive', () => {
    fc.assert(
      fc.property(tasksArb, (tasks) => {
        const incompleteCount = tasks.filter(t => !t.completed).length;
        const result = clearCompleted(tasks);
        expect(result).toHaveLength(incompleteCount);
      })
    );
  });
});

// ---------------------------------------------------------------------------
// P-4: Toggle idempotency
// Toggling the same task twice returns it to its original completed state.
// ---------------------------------------------------------------------------
describe('P-4: toggleTask idempotency', () => {
  it('double-toggling a task leaves it in its original completed state', () => {
    fc.assert(
      fc.property(nonEmptyTasksArb, (tasks) => {
        const target = tasks[0];
        const originalState = target.completed;

        const oncToggled  = toggleTask(tasks, target.id);
        const twiceToggled = toggleTask(oncToggled, target.id);

        const finalTask = twiceToggled.find(t => t.id === target.id);
        expect(finalTask).toBeDefined();
        expect(finalTask.completed).toBe(originalState);
      })
    );
  });

  it('toggling flips the completed flag', () => {
    fc.assert(
      fc.property(nonEmptyTasksArb, (tasks) => {
        const target = tasks[0];
        const result = toggleTask(tasks, target.id);
        const toggled = result.find(t => t.id === target.id);
        expect(toggled.completed).toBe(!target.completed);
      })
    );
  });
});

// ---------------------------------------------------------------------------
// P-5: deleteTask correctness
// After deleteTask(tasks, id), no task with that id remains.
// ---------------------------------------------------------------------------
describe('P-5: deleteTask removes the target task', () => {
  it('the deleted task id is absent from the result', () => {
    fc.assert(
      fc.property(nonEmptyTasksArb, (tasks) => {
        const target = tasks[0];
        const result = deleteTask(tasks, target.id);
        const found  = result.find(t => t.id === target.id);
        expect(found).toBeUndefined();
      })
    );
  });

  it('deleting one task reduces the list length by exactly 1', () => {
    fc.assert(
      fc.property(nonEmptyTasksArb, (tasks) => {
        const target = tasks[0];
        const result = deleteTask(tasks, target.id);
        expect(result).toHaveLength(tasks.length - 1);
      })
    );
  });

  it('tasks other than the deleted one are preserved', () => {
    fc.assert(
      fc.property(nonEmptyTasksArb, (tasks) => {
        const target  = tasks[0];
        const result  = deleteTask(tasks, target.id);
        const others  = tasks.filter(t => t.id !== target.id);
        expect(result.map(t => t.id)).toEqual(others.map(t => t.id));
      })
    );
  });
});
